version: "{build}"

os: Windows Server 2012

platform:
  - x86

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

clone_folder: c:\projects\CustomActionFastMsi

artifacts:
  - path: CustomActionFastMsi\bin
    name: Binaries
    type: zip

deploy:
  provider: GitHub
  artifact: CustomActionFastMsi\bin
  auth_token:
    secure: Fuf+0Vu0gan1h6l5WaH66HQm/OEF1O1HyeBr4zLqbQcNLkeNWuQun1g47O5yhYwj
  on:
    branch: master
    appveyor_repo_tag: true
